version: '3'

services:
  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
      - "443:443"
    restart: on-failure
  weather_db:
    image: postgres
    environment:
      POSTGRES_DB: weather_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
  weather_rest_api:
    build: .
    entrypoint: /rest/docker-entrypoint.sh
    volumes:
      - .:/rest
    ports:
      - "8000:8000"
    depends_on:
      - weather_db
    restart: on-failure