version: '3'

services:
  weather_db:
    image: postgres
    environment:
      POSTGRES_DB: weather_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5558:5432"
  weather_rest_api:
    build: .
    entrypoint: /rest/docker-entrypoint_last.sh
    volumes:
      - .:/rest
    ports:
      - "8000:8000"
    depends_on:
      - weather_db
    restart: on-failure
  my-app:
    container_name: my-app
    build: ./my-app
    volumes:
      - ./my-app:/app
      - /app/node_modules
    ports:
      - '8081:8080'
    restart: on-failure